config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }

  root 'homepage#index'

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]

  end

  resources :users, only: [:show] do
    resources :notes, except: [:index]
    resources :charactersheets, except: [:index]
    namespace :api do
      namespace :v1 do
        resources :charactersheets, only: [:show]
      end
    end
  end

  resources :map, only: [:index]

  resources :search, only: [:index] do
    get :advanced, on: :collection
  end

  resources :charviews, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :usage, only: [:index]
end

app/models/note.rb
class Note < ApplicationRecord
  validates :body, presence: true
  validates :title, presence: true

  belongs_to :game
  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @user = current_user
    if @user.games == []
      flash[:notice] = 'You need to join a game in order to create notes'
      redirect_back(fallback_location: user_path(@user))
    else
      @note = Note.new
      @games = []
      current_user.games.each do |game|
        @games << game.name
      end
    end
  end

  def create
    @note = Note.create(note_params)
    @game = Game.where(name: params[:note][:game]).first
    @note.game = @game
    @note.user = current_user

    if @note.save
      flash[:notice] = 'Note saved'
    else
      flash[:notice] = 'Error'
    end
    redirect_to game_path(@game)
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    @note.update_attributes(note_params)
    @game = @note.game

    if @note.save
      flash[:notice] = 'Note saved'
    else
      flash[:notice] = 'Error'
    end
    redirect_to game_path(@game)
  end

  def destroy
    @note = Note.find(params[:id])
    @game = @note.game

    if @note.delete
      flash[:notice] = 'Note deleted'
    else
      flash[:notice] = 'Error'
    end
    redirect_to game_path(@game)
  end

  private

  def note_params
    params.require(:note).permit(
      :title,
      :body
    )
  end
end

app/views/notes/edit.html.erb
<div id='background'>
  <h1>Edit Note:</h1>
  <h3>Title: <%= @note.title %></h3>
  <%= form_for [current_user, @note] do |f| %>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 20 %>
    </div>

    <%= f.submit id: 'special' %>

  <% end %>
  <%= button_to 'Delete Note', user_note_path(@note), method: :delete, id: 'special'  %>
</div>

app/views/notes/new.html.erb
<div id='background'>
  <h1>New Note:</h1>
  <%= form_for [current_user, @note] do |f| %>

    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 10 %>
    </div>

    <div>
      <%= f.label :game %>
      <%= f.select :game, @games %>
    </div>

    <%= f.submit id: 'special'%>

  <% end %>
</div>