config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }

  root 'homepage#index'

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]

  end

  resources :users, only: [:show] do
    resources :notes, except: [:index]
    resources :charactersheets, except: [:index]
    namespace :api do
      namespace :v1 do
        resources :charactersheets, only: [:show]
      end
    end
  end

  resources :map, only: [:index]

  resources :search, only: [:index] do
    get :advanced, on: :collection
  end

  resources :charviews, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :usage, only: [:index]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @games = []
    if params[:search]
      @search = params[:search]
      @games = Game.where('name  ~* ?', "#{@search}").order(name: :asc)
    end
  end

  def advanced
    @games = []
    @name = params[:name]
    @type = params[:type]
    @day = params[:day]
    @frequency = params[:freq]
    @dmname = params[:dm]
    if @dmname != ''
      @dm_id = User.where(username: @dmname)
    end
    if params[:name] || params[:type] || params[:day] || params[:freq] || params[:dm]
      @games = Game.where('name  ~* ?', "#{@name}").order(name: :asc)
      @games = @games.where('gametype  ~* ?', "#{@type}").order(name: :asc)
      @games = @games.where('day  ~* ?', "#{@day}").order(name: :asc)
      @games = @games.where('frequency  ~* ?', "#{@frequency}").order(name: :asc)
      if @dm_id
        @games = @games.where(dm_id: @dm_id).order(name: :asc)
      end
    end
  end
end

app/views/search/advanced.html.erb
<div id='background'>
  <div class='medium-12 columns'>
    <div class='medium-10 columns medium-offset-1 columns'>
      <p>
        <%= form_tag(advanced_search_index_path, :method => "get") do %>
          <div class='medium-12 columns'><%= text_field_tag :name, params[:name], placeholder: "Search Game Listings By Name" %></div>
          <div class='medium-6 columns'><%= text_field_tag :type, params[:type], placeholder: "Search Game Listings By Game Type" %></div>
          <div class='medium-6 columns'><%= text_field_tag :day, params[:day], placeholder: "Search Game Listings By Weekday" %></div>
          <div class='medium-6 columns'><%= text_field_tag :freq, params[:freq], placeholder: "Search Game Listings By Frequency" %></div>
          <div class='medium-6 columns'><%= text_field_tag :dm, params[:dm], placeholder: "Search Game Listings By DM Name (Exact matches only)" %></div>
          <div class='medium-4 medium-offset-4 columns float-left' style='padding-bottom: 1%;'><%= submit_tag "Search", id: 'button'%></div>
        <% end %>
      </p>
    </div>
  </div><div style='color: transparent;'>.</div>

  <% if @name || @type || @day || @dm %>
    <% @games.each do |game| %>
      <p>
        <u><%= link_to game.name, game_path(game) %></u>:
        <% if game.description.length > 175 %>
          <%= game.description[0...175] %>...(click the game name to see more)
        <% else %>
          <%= game.description %>
        <% end %>
        <br />What: <%= game.gametype %>
        <br />Where: <%= game.location %> // When: <%= game.frequency %>, <%= game.day %>s at <%= DateTime.parse(game.time).strftime("%l:%M%p") %>
        // Players: <%= game.playernum %>
        <hr />
      </p>
    <% end %>
    <% if @games != [] %>
      <div class='text-center' id='out'>
        <h5>Oops, all out of games!</h5>
      </div>
    <% else %>
      <div class='text-center'>
        <h5>There are no games that match your search criteria</h5>
      </div>
    <% end %>
  <% end %>
</div>

app/views/search/index.html.erb
<div class='medium-12 columns'>
  <div class='medium-8 columns medium-offset-2 columns'>
    <p>
      <%= form_tag(search_index_path, :method => "get") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Game Listings By Name" %>
        <div class='text-center medium-2 medium-offset-5 columns float-left' style='padding-bottom: 1%;'><%= submit_tag "Search", id: 'button'%></div>
        <div class='text-center medium-2 medium-offset-5 columns float-left'><%= link_to 'Advanced Search', advanced_search_index_path, method: :get, id: 'special'%> </div>
      <% end %>
    </p>
  </div>
</div>

<% if @search %>
  <div id='background'>
    <% @games.each do |game| %>
      <p>
        <u><%= link_to game.name, game_path(game) %></u>:
        <% if game.description.length > 175 %>
          <%= game.description[0...175] %>...(click the game name to see more)
        <% else %>
          <%= game.description %>
        <% end %>
        <br />What: <%= game.gametype %>
        <br />Where: <%= game.location %> // When: <%= game.frequency %>, <%= game.day %>s at <%= DateTime.parse(game.time).strftime("%l:%M%p") %>
        // Players: <%= game.playernum %>
        <hr />
      </p>
    <% end %>
    <% if @games != [] %>
      <div class='text-center' id='out'>
        <h5>Oops, all out of games!</h5>
      </div>
    <% else %>
      <div class='text-center'>
        <h5>There are no games that match your search criteria</h5>
      </div>
    <% end %>
  </div>
<% end %>