config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }

  root 'homepage#index'

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]

  end

  resources :users, only: [:show] do
    resources :notes, except: [:index]
    resources :charactersheets, except: [:index]
    namespace :api do
      namespace :v1 do
        resources :charactersheets, only: [:show]
      end
    end
  end

  resources :map, only: [:index]

  resources :search, only: [:index] do
    get :advanced, on: :collection
  end

  resources :charviews, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :usage, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_many :signups
  has_many :games, through: :signups
  has_many :requests
  has_many :comments
  has_many :notes
  has_many :charactersheets
  has_many :charviews
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if user_signed_in?
      @user = current_user
      @views = []
      @user.charactersheets.each do |sheet|
        @views += sheet.charviews
      end
      @charview = Charview.new
      @shared = Charview.where(user: current_user)
    else
      flash[:notice] = 'Please sign in first'
      redirect_to new_user_session_path
    end
  end
end

app/views/users/show.html.erb
<div id='background' class='small-12 columns medium-8 columns float-left'>
  <div class='small-12 columns'>
    <div class='medium-9 columns'>
      <h1><%= @user.username %>'s Profile Page:</h1>
    </div>
      <div class='medium-3 columns'>
        <%= button_to 'Edit Profile', edit_user_registration_path(current_user), method: :get, id: 'button' %>
      </div>
  </div>

  <h2>Your Games:</h2>
    <% @user.signups.each do |signup| %>
        <%= link_to signup.game.name, game_path(signup.game) %>
          <% if signup.game.dm_id == @user.id %>
            (DM)
          <% end %>
      <br />
    <% end %>
    <hr />

  <h2>Your Requests:</h2>
    <% if @user.requests == [] %>
      No requests made.
    <% end %>
    <% @user.requests.each do |request| %>
      <p>
        <div class='small-9 columns'><%= link_to request.game.name, game_path(request.game) %></div>
        <%= button_to 'Cancel Request', game_request_path(request.game, request), method: :delete, id: 'special' %>
      </p>
    <% end %>
    <hr />

  <h2>Resources:</h2>
  ---------------
    <h3>Notes:</h3>
    <% if @user.notes == [] %>
      No notes created.
    <% end %>
      <% @user.notes.order(game_id: :asc).each do |note| %>
        <%= note.game.name %>: '<%= link_to note.title, edit_user_note_path(note.user, note.id), method: :get %>' - Last updated: <%= time_ago_in_words(note.updated_at) %> ago<br />
      <% end %>

    <h3>Characters:</h3>
    <% if @user.charactersheets == [] %>
      No characters created.
    <% end %>
      <% @user.charactersheets.order(name: :asc).each do |sheet| %>
        <div class='medium-10 columns float-left'>
          <%= link_to sheet.name, user_charactersheet_path(@user, sheet) %>: <%= sheet.race %> <%= sheet.classtype %>
        </div>
        <div class='medium-2 columns float-right'>
          <%= button_to 'Edit', edit_user_charactersheet_path(sheet), method: :get, id: 'button' %>
        </div><br />
      <% end %>
</div>

<div class='medium-4 columns float-right'>
  <div id='background' class='medium-11 columns float-right'>

    <iframe src="http://a.teall.info/dice/" width="100%" height="450">
      <p>Your browser does not support iframes.</p>
    </iframe>

    <%= button_to 'Create New Game', new_game_path, method: :get, id: 'button' %>
    <%= button_to 'Create New Note', new_user_note_path(@user), method: :get, id: 'button' %>
    <%= button_to 'Create New Character', new_user_charactersheet_path(@user), method: :get, id: 'button' %>
    <%= button_to 'Create New Shared View', new_charview_path(@charview), method: :get, id: 'button' %>

    <h3>Your Shared Views:</h3>
    <% if @views == [] %>
      No shared views yet!
    <% end %>
    <% @views.each do |view| %>
      <%= view.charactersheet.name %>: Able to be viewed by <%= view.user.username %><br />
      <%= button_to 'Delete Shared View', charview_path(view), method: :delete, id: 'special' %>
    <% end %>
    <h3>Views Shared with You:</h3>
    <% if @shared == [] %>
      No shared views yet!
    <% end %>
    <% @shared.each do |shared| %>
      <%= link_to shared.charactersheet.name, user_charactersheet_path(shared.charactersheet.user, shared.charactersheet) %>: Owned by: <%= shared.charactersheet.user.username %>
    <% end %>
  </div>
</div>