config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations/registrations'
  }

  root 'homepage#index'

  resources :games do
    resources :signups, only: [:create, :destroy]
    resources :requests, only: [:create, :destroy]
    resources :comments, only: [:create]

  end

  resources :users, only: [:show] do
    resources :notes, except: [:index]
    resources :charactersheets, except: [:index]
    namespace :api do
      namespace :v1 do
        resources :charactersheets, only: [:show]
      end
    end
  end

  resources :map, only: [:index]

  resources :search, only: [:index] do
    get :advanced, on: :collection
  end

  resources :charviews, only: [:new, :create, :destroy]

  resources :conversations do
    resources :messages
  end

  resources :usage, only: [:index]
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @games = Game.where.not(lat: nil).where.not(lat: 0).where.not(lat: 1)
    @unlisted = Game.where(lat: nil)
    @unlisted += Game.where(lat: 1)
    @hash = Gmaps4rails.build_markers(@games) do |game, marker|
      marker.lat game.lat
      marker.lng game.lng
      marker.title game.name
      marker.infowindow "<h6><a href='/games/" + game.id.to_s + "'>" + game.name + "</a></h6><p>Address: " + game.location + "<br/>Description: " + game.description + "</p>"
    end
  end
end

app/views/map/index.html.erb
<script src="//maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_JAVASCRIPT_KEY'] %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<div id = 'background' class='small-12 columns medium-8 columns large-8 columns'>
  <div id="map" style='width: 100%; height: 400px;'></div>
  Map centered on your location if geolocation is enabled and secure origin.
</div>
<div id = 'background' class='small-12 columns medium-4 columns large-4 columns'>
  <h3>Unlisted or Online Games:</h3>
  <% @unlisted.each do |game| %>
    <p><%= link_to game.name, game_path(game) %>
      <br/>Location: <%= game.location %></p>
  <% end %>
  <hr />
  <div class='text-center'>
    <h4>Don't See the Game You Want?</h4>
  </div>
  <div class='medium-8 columns medium-offset-2 columns float-left'>
    <%= button_to 'Search Games', search_index_path, method: :get, id: 'button' %>
  </div><div class='medium-8 columns medium-offset-2 columns float-left'>
    <%= button_to 'See All Games', games_path, method: :get, id: 'button' %>
  </div><div class='medium-8 columns medium-offset-2 columns float-left'>
    <%= button_to 'List a New Game', new_game_path, method: :get, id: 'button' %>
  </div>
</div>

<script type='text/javascript'>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    if(navigator.geolocation)
    navigator.geolocation.getCurrentPosition(displayOnMap);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
  function displayOnMap(position){
  var marker = handler.addMarker({
    lat: position.coords.latitude,
    lng: position.coords.longitude,
    infowindow: 'Your position'
  });
  handler.map.centerOn(marker);
}
</script>